INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido da Social Democracia Brasileira', 'PSDB', 'CENTRO', '1988-06-25')
INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido Democrático Trabalhista', 'PDT', 'ESQUERDA', '1979-06-17')
INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido Socialista Brasileiro', 'PSB', 'ESQUERDA', '1947-08-06')
INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Movimento Democrático Brasileiro', 'MDB', 'CENTRO', '1980-01-15')
INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Progressistas', 'PP', 'DIREITA', '1995-08-08')
INSERT INTO PARTIDOS(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido Novo', 'NOVO', 'DIREITA', '2011-05-12')


INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('Junior', 'PRESIDENTE', '1999-01-30', 'MASCULINO')
INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('Denise', 'DEPUTADO_ESTADUAL', '1998-02-18', 'FEMININO')
INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('Vinicius', 'PRESIDENTE', '1998-08-29', 'MASCULINO')
INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('Flavia', 'VEREADOR', '1996-10-29', 'FEMININO')
INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('João', 'PREFEITO', '1995-11-13', 'MASCULINO')
INSERT INTO ASSOCIADO(NOME, CARGOS_POLITICOS, DATA_NASCIMENTO, SEXO) VALUES ('Adjair', 'VEREADOR', '1974-11-01', 'MASCULINO')